sequenceDiagram
  ALT Begin write sequence diagram from here
    {Client} ->> {app}: Request to run worker
    ALT Start a worker
      LOOP infinity
        {Worker} ->> {Worker}: Print ok to screen
      END
    END
    note right of {Client}: Note client here
    PAR Get user
      %% HttpUser.getUser
        ALT is admin
          {app} ->> {app}: print the role to screen
        ELSE is not admin
          {app} ->> {LogService}: Add log to server
        END
        LOOP in 10 times
          {app} ->> {app}: print index to screen
        END
    AND Get company
      %% HttpUser.getCompany
        {app} --) {Redis}: Publish hello
        {app} ->> {LogService}: Make a request to add log
        {RabbitMQ} -) {app} : Comsume event
    END
    {app} -->> {Client} : Response "OK"
  END
