sequenceDiagram

    Client ->> Service: Get user information
    Note right of Service: note right here
    Note left of Service: note left here
    Note over Service,Redis: note over here

      PAR  Start worker
        LOOP 
          Service ->> Service: Do something here
        END 
      END 

      Service ->> UserService: Get user by id
      alt Check user id must be greater than 0
      Service -->> Service: Return user information
      else
      Service -->> Service: Return null
      end

      Service -) CompanyService: Request to get company infor
      Service -->> Redis: Pub data
      PAR  Push to sync
        Service -->> RabbitMQ: Sync data
      AND DO SOMETHING
        Service -->> KAFKA: Sync data
      END 
      CompanyService --) Service : Return company info
          ALT  User not existed
            Service ->> Service: Print user to console
            LOOP  i from 0 to 10
              Service ->> Service: Print i to console
            END 
          ELSE User existed
            Service ->> Service: Return user
          END 
          Service -->> Client : Return user information
