sequenceDiagram
    %% > HttpUser.userController
    Client -) Service: Add something
    PAR Run worker
      %% > HttpUser.workerRun
      LOOP Forever
        Service ->> Service: Log ok
      END 
      %% < HttpUser.workerRun
    END 
      %% > HttpUser.getUser
    ALT id > 0
      Service ->> Service: Return {name}
    ELSE Return null
    END 
      %% < HttpUser.getUser
      %% > HttpUser.getCompany
    Service -->> Redis: Hello
    Service -) RabbitMQ: hello
    Service --) Kafka : HEllo
      %% < HttpUser.getCompany
    ALT Not user
      Service ->> Service: Log user
      LOOP i in 10
        Service ->> Service: Log i
      END 
    ELSE return user
    END 
    NOTE RIGHT OF Service undefined: Here
    Service --) Client : Return user
    %% < HttpUser.userController
