graph LR
Client --Request--> app
app --Call--> MongoDB
app --Request--> UserCore
app --Publish--> RabbitMQ
app --Request--> Workspace
app --Call--> Redis
RabbitMQ --Consume--> app
Workspace --Publish--> RabbitMQ
Redis --Consume--> app
ScheduleWorker --Publish--> Redis
