sequenceDiagram

  %% > userController.importMultiple
    Client -) Service: Import users from excel file

    %% > apiUserService.importMultiple
    Service ->> Mongo: Get invite user
    Service ->> Mongo: Get workspace info
    Mongo -->> Service : Return invite user infor
    Mongo -->> Service : Get workspace info
    ALT Workspace not existed
      Service --) Client : Return error: Workspace not found
    ELSE 

      %% > apiUserService.parseFile
      %% < apiUserService.parseFile

    END 
    %% < apiUserService.importMultiple

    Service --) Client : Return { workspace_id, userCount, err }
  %% < userController.importMultiple

