sequenceDiagram
  %% COMMENT
    Client ->> App: Request to run worker
    OPT Start a worker
      LOOP infinity
        Worker ->> Worker: Print ok to screen
      END
    END
    NOTE RIGHT OF Client: Note right of client
    NOTE LEFT OF Client: Note left of client
    PAR Get user
      %% HttpUser.getUser
        ALT is admin
          App ->> App: print the role to screen
        ELSE is not admin
          App ->> LogService: Add log to server
        END
        LOOP in 10 times
          App ->> App: print index to screen
        END
    AND Get company
      %% HttpUser.getCompany
        App --) Redis: Publish hello
        App ->> LogService: Make a request to add log
        RabbitMQ -) App : Comsume event
    END
    NOTE OVER Client, RabbitMQ: Message over here
    App -->> Client : Response "OK"
