sequenceDiagram
  %% COMMENT
    Client ->> Test_service: Request to run worker
    OPT Start a worker
      LOOP infinity
        Worker ->> Worker: Print ok to screen
      END
    END
    NOTE RIGHT OF Client: Note right of client
    NOTE LEFT OF Client: Note left of client
    PAR Get user
      %% HttpUser.getUser
        ALT is admin
          Test_service ->> Test_service: print the role to screen
        ELSE is not admin
          Test_service ->> LogService: Add log to server
        END
        LOOP in 10 times
          Test_service ->> Test_service: print index to screen
        END
    AND Get company
      %% HttpUser.getCompany
        Test_service --) Redis: Publish hello
        Test_service ->> LogService: Make a request to add log
        RabbitMQ -) Test_service : Comsume event
    END
    NOTE OVER Client, RabbitMQ: Message over here
    Test_service -->> Client : Response "OK"
