flowchart LR
%% Test service
classDef Services fill:#74d2e7,color:#fff;
classDef App fill:#0cb9c1,color:#fff;
CLIENT{{"☺ ☺ ☺ <br/> Client"}}:::Client
  TESTSERVICE("⌬ <br/> Test service"):::App
subgraph Other-Services
    LOGSERVICE("⌬ <br/> LogService"):::Services
    REDIS("⌬ <br/> Redis"):::Services
    RABBITMQ("⌬ <br/> RabbitMQ"):::Services
end
CLIENT ---->| Request to run worker| TESTSERVICE
TESTSERVICE ---->| Add log to server| LOGSERVICE
TESTSERVICE -...->| Publish hello| REDIS
TESTSERVICE ---->| Make a request to add log| LOGSERVICE
RABBITMQ -...->| Comsume event| TESTSERVICE
linkStyle 0 fill:none,stroke:#0cb9c1,stroke-width:1px;
linkStyle 1 fill:none,stroke:#0cb9c1,stroke-width:1px;
linkStyle 2 fill:none,stroke:#f48924,stroke-width:1px;
linkStyle 3 fill:none,stroke:#0cb9c1,stroke-width:1px;
linkStyle 4 fill:none,stroke:#f48924,stroke-width:1px;