sequenceDiagram
  %% COMMENT
    Client ->> app: Request to run worker
    OPT Start a worker
      LOOP infinity
        Worker ->> Worker: Print ok to screen
      END
    END
    NOTE RIGHT OF Client: Note right of client
    NOTE LEFT OF Client: Note left of client
    PAR Get user
      %% HttpUser.getUser
        ALT is admin
          app ->> app: print the role to screen
        ELSE is not admin
          app ->> LogService: Add log to server
        END
        LOOP in 10 times
          app ->> app: print index to screen
        END
    AND Get company
      %% HttpUser.getCompany
        app --) Redis: Publish hello
        app ->> LogService: Make a request to add log
        RabbitMQ -) app : Comsume event
    END
    NOTE OVER Client, RabbitMQ: Message over here
    app -->> Client : Response "OK"
